//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuesto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        public string Usuario { get; set; }
        public int Administracion { get; set; }
        public int Solicitar_Modificacion { get; set; }
        public int Responder_Solicitudes { get; set; }
    }
}
