//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuesto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitudes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitudes()
        {
            this.Historico = new HashSet<Historico>();
        }
    
        public int idSolicitud { get; set; }
        public int idTipoSolicitud { get; set; }
        public int idSolicitante { get; set; }
        public int idPeriodo { get; set; }
        public int idDepartamento_Origen { get; set; }
        public string CodPartida_Origen { get; set; }
        public int idDepartamento_Destino { get; set; }
        public string CodPartida_Destino { get; set; }
        public decimal Monto_Solicitado { get; set; }
        public System.DateTime Fecha_Solicitud { get; set; }
        public System.DateTime Fecha_Respuesta { get; set; }
        public int idEstado { get; set; }
    
        public virtual Cat_Departamentos Cat_Departamentos { get; set; }
        public virtual Cat_Departamentos Cat_Departamentos1 { get; set; }
        public virtual Cat_Estado_Solicitud Cat_Estado_Solicitud { get; set; }
        public virtual Cat_Periodo_Modificaciones Cat_Periodo_Modificaciones { get; set; }
        public virtual Cat_Solicitudes Cat_Solicitudes { get; set; }
        public virtual Empleados Empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historico> Historico { get; set; }
    }
}
