//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuesto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ver_Presupuestos
    {
        public int Depto { get; set; }
        public string Nombre { get; set; }
        public decimal Presupuesto_autorizado { get; set; }
        public Nullable<decimal> Presupuesto_asignado { get; set; }
    }
}
