//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuesto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ver_Cod_Partidas_Asignadas
    {
        public int IdDepto { get; set; }
        public string Departamento { get; set; }
        public string Cod { get; set; }
        public string Partida { get; set; }
        public Nullable<decimal> Monto_asignado { get; set; }
    }
}
