//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuesto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ver_Historico
    {
        public int Periodo { get; set; }
        public int Solicitud { get; set; }
        public string Tipo { get; set; }
        public System.DateTime Fecha_Solicitud { get; set; }
        public System.DateTime Fecha_Respuesta { get; set; }
        public string Depto_Origen { get; set; }
        public string Cod_Partida { get; set; }
        public string Partida_Origen { get; set; }
        public decimal Saldo_Inicial { get; set; }
        public decimal Monto_Solicitud { get; set; }
        public Nullable<decimal> Nuevo_Saldo { get; set; }
        public string Depto_Destino { get; set; }
        public string Cod_Partida_Destino { get; set; }
        public string Partida_Destino { get; set; }
        public Nullable<decimal> Saldo_Inicial_Destino { get; set; }
        public decimal Monto__Solicitud { get; set; }
        public Nullable<decimal> Nuevo_Saldo_Destino { get; set; }
        public string Solicitante { get; set; }
        public string Analista_Responsable { get; set; }
        public string Estado_Solicitud { get; set; }
    }
}
